Avoid slack ratelimiter failures when decoding channels and users
yougov/pmxbot pull request #111
Opened 2024-04-03 16:49 UTC by csuriano23

This MR include the following activities:

1. Restore the `__init__` file on main module, needed for starting and importing properly

2. Change the way in which users and channels are retrieved from Slack APIs, adding a timed cache layer on top of the integration. This is needed since too many concurrent calls without a capacious [pricing Tier](https://api.slack.com/apis/rate-limits) lead to unresolved channel and/or mentions (eg. when in a message we are tagging multiple users). This new approach is more needy from a memory point of view (replacing the paged iterator to a cached dictionary), but more stable and, in fact, memory should not exceed a few megabytes for hundreds of thousands users

2024-04-05 10:51 UTC, adriandiazgar commented
Hi @chrisBrookes93,  @andrepedroso already approved the pull request, but it would be great if you could also take a look and let us know if you feel it's ok to merge this.

2024-04-05 14:16 UTC, chrisBrookes93 commented
LGTM

2024-04-05 14:16 UTC, chrisBrookes93 approved these changes

2024-04-05 14:31 UTC, adriandiazgar commented
Hello @jaraco after @andrepedroso and @chrisBrookes93 took a look into that.
Would you please be able to take a look, review and if everything is fine merge it?

Thanks in advance

2024-04-06 19:40 UTC, chrisBrookes93 requested changes
I tested this with our pmxbot instance. Whilst the changes work, quite often requests are failing with an `IncompleteRead` issue:

![image](https://github.com/pmxbot/pmxbot/assets/1598192/180044ef-07d1-4ebd-8c39-57234935f920)


My guess would be that we're trying to pull back too much information from the slack servers in one go. I suggest we decrease the page size just a little

2024-04-07 05:21 UTC, csuriano23 commented
> I tested this with our pmxbot instance. Whilst the changes work, quite often requests are failing with an `IncompleteRead` issue:
> 
> ![image](https://private-user-images.githubusercontent.com/1598192/320230714-180044ef-07d1-4ebd-8c39-57234935f920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjYwMjYsIm5iZiI6MTcxMjQ2NTcyNiwicGF0aCI6Ii8xNTk4MTkyLzMyMDIzMDcxNC0xODAwNDRlZi0wN2QxLTRlYmQtOGMzOS01NzIzNDkzNWY5MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDQ1NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE3NzE5YzhjYWI3ZTQyYzBkNjIyZDgyZDUzYzgyYTRkY2RjNjY5MGUzNGQ2N2VhNGY2YzM5MWVmNjU1ZDk2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GWmx0Mp6zlrIn5RhjFimY4DqmClsZMVen_hGR_jdeCg)
> 
> My guess would be that we're trying to pull back too much information from the slack servers in one go. I suggest we decrease the page size just a little

Hi Chris, thank you for pointing out.
I see this as a bit weird, since the current version is not [applying any limit](https://github.com/pmxbot/pmxbot/blob/main/pmxbot/slack.py#L141) (no param set defaults to 0, which means [unlimited results](https://api.slack.com/methods/users.list#arg_limit)).
I would expect that any limit set here would only be an improvement.

Since `slack_cache_ttl` is meant to be configurable, we can easily lowen the default limit too, but I would like to understand what's going on, since on a local py3.8 with the same slack-sdk lib version I couldn't reproduce the issue. Can you provide furher details on how you got the error?

2024-04-07 10:22 UTC, chrisBrookes93 commented
> I tested this with our pmxbot instance. Whilst the changes work, quite often requests are failing with an `IncompleteRead` issue:
> 
> ![image](https://private-user-images.githubusercontent.com/1598192/320230714-180044ef-07d1-4ebd-8c39-57234935f920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzQxMjAsIm5iZiI6MTcxMjQzMzgyMCwicGF0aCI6Ii8xNTk4MTkyLzMyMDIzMDcxNC0xODAwNDRlZi0wN2QxLTRlYmQtOGMzOS01NzIzNDkzNWY5MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMjAwMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzc2YmM4YTJjZTE5MDM2YmVkMDFmZTcyMmJiMDE1ZjJjNThmYzFiMTkzMTMxNjRmODU4Yjc3OGEwZmUyMDYyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.slW7j0QXi_TQocFJlLVcBNq941B7P6nvQZlGCf9z3Ck)
> 
> My guess would be that we're trying to pull back too much information from the slack servers in one go. I suggest we decrease the page size just a little



> > I tested this with our pmxbot instance. Whilst the changes work, quite often requests are failing with an `IncompleteRead` issue:
> > ![image](https://private-user-images.githubusercontent.com/1598192/320230714-180044ef-07d1-4ebd-8c39-57234935f920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjYwMjYsIm5iZiI6MTcxMjQ2NTcyNiwicGF0aCI6Ii8xNTk4MTkyLzMyMDIzMDcxNC0xODAwNDRlZi0wN2QxLTRlYmQtOGMzOS01NzIzNDkzNWY5MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDQ1NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE3NzE5YzhjYWI3ZTQyYzBkNjIyZDgyZDUzYzgyYTRkY2RjNjY5MGUzNGQ2N2VhNGY2YzM5MWVmNjU1ZDk2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GWmx0Mp6zlrIn5RhjFimY4DqmClsZMVen_hGR_jdeCg)
> > My guess would be that we're trying to pull back too much information from the slack servers in one go. I suggest we decrease the page size just a little
> 
> Hi Chris, thank you for pointing out. I see this as a bit weird, since the current version is not [applying any limit](https://github.com/pmxbot/pmxbot/blob/main/pmxbot/slack.py#L141) (no param set defaults to 0, which means [unlimited results](https://api.slack.com/methods/users.list#arg_limit)). I would expect that any limit set here would only be an improvement.
> 
> Since `slack_cache_ttl` is meant to be configurable, we can easily lowen the default limit too, but I would like to understand what's going on, since on a local py3.8 with the same slack-sdk lib version I couldn't reproduce the issue. Can you provide furher details on how you got the error?

In fairness this **could** have been my WiFi or VPN (which has been a little problematic this week). I am ok with sticking with the maximum as the default for now and testing in production to see if we encounter the same issue. But can we extend the code where we initialise the `Bot` class [here](https://github.com/pmxbot/pmxbot/blob/main/pmxbot/core.py#L594) to allow both of these values to be set via config please? To strengthen the case for this, the docs ([here](https://api.slack.com/apis/pagination#:~:text=subject%20to%20change%20and%20may%20vary%20per%20method)) say that this limit is "subject to change"

2024-04-08 11:58 UTC, csuriano23 commented
> > I tested this with our pmxbot instance. Whilst the changes work, quite often requests are failing with an `IncompleteRead` issue:
> > ![image](https://private-user-images.githubusercontent.com/1598192/320230714-180044ef-07d1-4ebd-8c39-57234935f920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzQxMjAsIm5iZiI6MTcxMjQzMzgyMCwicGF0aCI6Ii8xNTk4MTkyLzMyMDIzMDcxNC0xODAwNDRlZi0wN2QxLTRlYmQtOGMzOS01NzIzNDkzNWY5MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMjAwMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzc2YmM4YTJjZTE5MDM2YmVkMDFmZTcyMmJiMDE1ZjJjNThmYzFiMTkzMTMxNjRmODU4Yjc3OGEwZmUyMDYyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.slW7j0QXi_TQocFJlLVcBNq941B7P6nvQZlGCf9z3Ck)
> > My guess would be that we're trying to pull back too much information from the slack servers in one go. I suggest we decrease the page size just a little
> 
> > > I tested this with our pmxbot instance. Whilst the changes work, quite often requests are failing with an `IncompleteRead` issue:
> > > ![image](https://private-user-images.githubusercontent.com/1598192/320230714-180044ef-07d1-4ebd-8c39-57234935f920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjYwMjYsIm5iZiI6MTcxMjQ2NTcyNiwicGF0aCI6Ii8xNTk4MTkyLzMyMDIzMDcxNC0xODAwNDRlZi0wN2QxLTRlYmQtOGMzOS01NzIzNDkzNWY5MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDQ1NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE3NzE5YzhjYWI3ZTQyYzBkNjIyZDgyZDUzYzgyYTRkY2RjNjY5MGUzNGQ2N2VhNGY2YzM5MWVmNjU1ZDk2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GWmx0Mp6zlrIn5RhjFimY4DqmClsZMVen_hGR_jdeCg)
> > > My guess would be that we're trying to pull back too much information from the slack servers in one go. I suggest we decrease the page size just a little
> > 
> > 
> > Hi Chris, thank you for pointing out. I see this as a bit weird, since the current version is not [applying any limit](https://github.com/pmxbot/pmxbot/blob/main/pmxbot/slack.py#L141) (no param set defaults to 0, which means [unlimited results](https://api.slack.com/methods/users.list#arg_limit)). I would expect that any limit set here would only be an improvement.
> > Since `slack_cache_ttl` is meant to be configurable, we can easily lowen the default limit too, but I would like to understand what's going on, since on a local py3.8 with the same slack-sdk lib version I couldn't reproduce the issue. Can you provide furher details on how you got the error?
> 
> In fairness this **could** have been my WiFi or VPN (which has been a little problematic this week). I am ok with sticking with the maximum as the default for now and testing in production to see if we encounter the same issue. But can we extend the code where we initialise the `Bot` class [here](https://github.com/pmxbot/pmxbot/blob/main/pmxbot/core.py#L594) to allow both of these values to be set via config please? To strengthen the case for this, the docs ([here](https://api.slack.com/apis/pagination#:~:text=subject%20to%20change%20and%20may%20vary%20per%20method)) say that this limit is "subject to change"

Good idea @chrisBrookes93, although not really straightforward to add without some refactorings.
I've merged a proposal in the PR

2024-04-08 12:31 UTC, chrisBrookes93 commented
@csuriano23 I was thinking about a lighter touch approach, something like...

```def initialize(config):
      ...
      ...
    config.setdefault('log_channels', [])
    config.setdefault('other_channels', [])

    # Alternative to the if statements added below and (then add these to bot_args)
    config.setdefault('slack_cache_ttl', DEFAULT_SLACK_CACHE_TTL)
    config.setdefault('slack_page_size', DEFAULT_SLACK_PAGE_SIZE)
    ##############################################

    log.info('Running with config')
    log.info(pprint.pformat(config))

    bot_args = {
        'host': config.get('server_host', 'localhost'),
        'port': config.get('server_port', 6667),
        'nickname': config.bot_nickname,
        'channels': config.log_channels + config.other_channels,
        'password': config.get('password')
    }
    if config.get('slack_cache_ttl'):
        bot_args['slack_cache_ttl'] = config.get('slack_cache_ttl')
    if config.get('slack_page_size'):
        bot_args['slack_page_size'] = config.get('slack_page_size')

    return class_(**bot_args)
```

What do you think about the above?

2024-04-08 12:38 UTC, csuriano23 commented
Unluckily
> return class_(**bot_args)

2024-04-08 14:25 UTC, chrisBrookes93 commented
Whilst there is more boilerplate code than I anticipated in your recent code change,  after taking a second look, I think what you have is a sensible way forward. LGTM, thanks!

2024-04-08 14:25 UTC, chrisBrookes93 approved these changes

2024-04-08 15:27 UTC, jaraco commented
The diffcov check indicates this change is missing one line:

pmxbot/core.py (88.9%): Missing lines 434

2024-04-08 15:27 UTC, merged

2024-04-08 15:46 UTC, jaraco commented
1122.17 is releasing now with the change.

2024-04-09 08:01 UTC, adriandiazgar commented
Thanks @jaraco !